baseURL = "/"
languageCode = "en-us"
title = "Dan Nolte"
themesDir = "themes"
theme = "hugo-whisper-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "DS Resources"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Resume"
    url = "/about/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'About Me'
  homepage_intro = 'Hi, Im Dan'
  homepage_image = '/images/bridge.jpeg'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "This is my personal site."
    meta_og_title = "Dan Nolte"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.app"
    meta_og_image = "/images/logo.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/logo.png"
      standard  = "/images/logo.png"
